import { Prisma } from '@prisma/client';
import type { LlmProvider, LlmProviderKind } from '@prisma/client';

import type { PrismaProvider } from './types.js';

export type { LlmProvider, LlmProviderKind };

export interface CreateLlmProviderInput {
  name: string;
  kind: LlmProviderKind;
  model: string;
  baseUrl?: string | null;
  apiKeyEnc?: Buffer | null;
  apiKeyLast4?: string | null;
  extra?: Prisma.InputJsonValue | null;
}

export interface UpdateLlmProviderInput {
  name?: string;
  model?: string;
  baseUrl?: string | null;
  apiKeyEnc?: Buffer | null;
  apiKeyLast4?: string | null;
  extra?: Prisma.InputJsonValue | null;
}

export class LlmProviderRepository {
  constructor(private readonly getPrisma: PrismaProvider) {}

  list(): Promise<LlmProvider[]> {
    return this.getPrisma().llmProvider.findMany({ orderBy: { createdAt: 'asc' } });
  }

  findById(id: string): Promise<LlmProvider | null> {
    return this.getPrisma().llmProvider.findUnique({ where: { id } });
  }

  create(input: CreateLlmProviderInput): Promise<LlmProvider> {
    const data: Prisma.LlmProviderCreateInput = {
      name: input.name,
      kind: input.kind,
      model: input.model,
    };
    if (input.baseUrl !== undefined) data.baseUrl = input.baseUrl;
    // Prisma's generated Bytes type is `Uint8Array<ArrayBuffer>` (strict);
    // a Buffer from node:crypto is a Buffer<ArrayBufferLike>. They're
    // structurally identical at runtime — coerce via a Uint8Array view.
    if (input.apiKeyEnc !== undefined) {
      data.apiKeyEnc = input.apiKeyEnc === null ? null : new Uint8Array(input.apiKeyEnc);
    }
    if (input.apiKeyLast4 !== undefined) data.apiKeyLast4 = input.apiKeyLast4;
    if (input.extra !== undefined && input.extra !== null) data.extra = input.extra;
    return this.getPrisma().llmProvider.create({ data });
  }

  update(id: string, input: UpdateLlmProviderInput): Promise<LlmProvider> {
    const data: Prisma.LlmProviderUpdateInput = {};
    if (input.name !== undefined) data.name = input.name;
    if (input.model !== undefined) data.model = input.model;
    if (input.baseUrl !== undefined) data.baseUrl = input.baseUrl;
    if (input.apiKeyEnc !== undefined) {
      data.apiKeyEnc = input.apiKeyEnc === null ? null : new Uint8Array(input.apiKeyEnc);
    }
    if (input.apiKeyLast4 !== undefined) data.apiKeyLast4 = input.apiKeyLast4;
    if (input.extra !== undefined) {
      data.extra = input.extra === null ? Prisma.JsonNull : input.extra;
    }
    return this.getPrisma().llmProvider.update({ where: { id }, data });
  }

  async delete(id: string): Promise<boolean> {
    const r = await this.getPrisma().llmProvider.deleteMany({ where: { id } });
    return r.count > 0;
  }
}
